language: ruby
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
rvm:
- 2.4.0
bundler_args: "--jobs=2"
script:
- bundle exec rake db:setup
- bundle exec rake spec
cache: bundler
services:
- postgresql
addons:
  postgresql: '9.4'
deploy:
  provider: heroku
  api_key:
    secure: yuQ90XdjxnfNkQv1nYUW7GUXRgJf/kYhrD8VBxl+6H4LSXMRxwSss1TGR51WqKY7xB/HsgckVC5CTJ7Z/Ot0paPwgkK+1yE6Vflyg0Evk1vkXoBp0TjQdld6IWgjh7B/4GjpH2rKmsuRQNHo6YCIf++hN9JeyTo7I5DG8vTCus7CUFIf88i+NtWC9GQXVhKjrEMnmWJJSO9CH3EBD+gjfd+k/iMgA6FeVpf8/snfdR57/V/mrI5KtOS4l8woNC1Ameiiy057YoAakQxPR3Mb3re153oOBD/QSuDKW/Ebciq+6SKmgfoCGCNLD/hd5be3B95pU8CFUdSsQ6sASCfz7TZ9jM9paeP9iQdHplxo7QCAxxlT2szwn3WJmp7bi8/yQmfcoyxs2bh/eQoio/yZmRBSJjgY/rwXcA5wu1vt0wtYl0weGj64FLQDZnnBR5mQnQ2yPibhiyTaIv1JY1ScXkZm2y99RY8/VoLZqcJBpso4mR7lBCqMAr2FRfo3uScLQIfk17fLP2Cq4XeIbvxKPplUC8/mjLI6eREIbcq0MjruhQeecjviDDe8gOtu1tcu2fbth3AIjNWeu3JFXkryBae4+KMo+YELqf42/f6uogx1tSjedklbJbKXAk8jxP73xEIciHx+vGukoN+6+ZKRuIY+94nkoV39xNlMCjMILdc=
  app: imkerij
  on:
    repo: Lubmes/Imkerij
  skip_cleanup: true
env:
  matrix:
  - s3_bucket='imkerij-poppendamme-dev'
  global:
  - secure: JfXzJTllzEt5yhUfGq1dC09y2YMKi5cLVEnfDOmKZ+O+YWRBsUnICI1I1zOyj6GVE2TiC3hC15HUGFlrOB1a6XsEhuVVjBPkLjbZRGLqF/EZn1QD+EPki7yk2Fo2M0Knye+iZftI6ah6IWsH+aAWt2Ro0T4xTi58tySRujRxAiUpczi3zAvGBnCszNEHVvJp7l0aBqpAkcF6QsO1fbgp1yV01bezPjQBjYiiU84ZLtpbVrgY8FM6Jf8FTAUm/p0zWgtawdQSOIMgc6mBKtPmo/WThB2vKnF4ccxENYn2KeUVs0ge97mT0KoNOIF4WqOQdH9mLo9H8DagrG7ngs8v/MrfDjMkWIT2sY4EUhPp7k+OiqZbexV6eZOgEiXfMwtBjPHlEcCiihBUNvi+JKiD+7LsHd+tuumArNUq5vxeY/9ZzxXnqjI6uElVuuy/smXr1/5Zz7wYPCN56b8rA+616TheByO+sqbzUWpTu019PIaCnIDOUog47apJqAD8lAyVqLK4ODx0N0IV0yA/r4hcFbe3ke/Fbk+7k5AL0yxDBvl4Yanq85wtFxFUwnjogbzaui37n/L+4hYYM6rPOg40zZxa3g0AwLFLn1ojXg3IJHy3UUQGwlDU6RHV3rQscRpHPkNy5PAgKAbbbTHhDQltzWMRzsMALsUNVNry8gvtAnc=
  - secure: ACqnA5KjPo442OYxGC63SM4qyrsX8HTKqGrfQrAB20NzpDcYj1U4EjhzM4TxiJCv+Lf4BDGxxu1PiXt6DWe4DoVHxGZro82g3RNFSHRXUNqfunXQ5CDtaBB4eKhA5tasOVKePQcRSH3B1wzPa1eJOVjtWz00v0X6D/VMJQW91rn5X+uDKpXk+lk0BoclfdlE4twMZvEVggJEQii+EPc4/OTSrbitpzhpqgHZgzlKYhlKms942kcsGqe4x+CClJrYtcL2MPt4RJOg2qeUfI2L7rwIguQnmAKCZUNV3yuJ2iYb2Ydoi0rpRL9ZzG43o0JA/lZWkCLM4vtRlROJ7WORuaCtUp4aW1wQSARlJWtzsyPCIW3mKdn7xXxhvlJsi0YTmNHlWQnVhoySjmwRpqDgcpofLhTYeRvnexzygdDrvqgX7KgPYjBx42APFXCWZXedGf4hMl5uR1TnFeCGRp/QpDnIA+1JNwkDTNtHKLqBXB0AgghKjGZn9i2Skl23YNnh+ynk2XQm2goUhlDQZr5Zp6hwnUmeAUkVFYBMBjejOoPDC2E55g3cCzNPHF5Q88CX3m+vFdJufw1K8CsDyIJLlw8m+lZ0JPOnUKMfzHamEjmuecgj3HgKK32rzVXKOc73ojfy/Jt9MoqmqF5JBIBbSLcDJgOT/pzRpIcGfb9+mIw=
