language: ruby
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
rvm:
- 2.4.0
bundler_args: "--jobs=2"
script:
- bundle exec rake db:setup
- bundle exec rake spec
cache: bundler
services:
- postgresql
addons:
  postgresql: '9.4'
deploy:
  provider: heroku
  api_key:
    secure: yuQ90XdjxnfNkQv1nYUW7GUXRgJf/kYhrD8VBxl+6H4LSXMRxwSss1TGR51WqKY7xB/HsgckVC5CTJ7Z/Ot0paPwgkK+1yE6Vflyg0Evk1vkXoBp0TjQdld6IWgjh7B/4GjpH2rKmsuRQNHo6YCIf++hN9JeyTo7I5DG8vTCus7CUFIf88i+NtWC9GQXVhKjrEMnmWJJSO9CH3EBD+gjfd+k/iMgA6FeVpf8/snfdR57/V/mrI5KtOS4l8woNC1Ameiiy057YoAakQxPR3Mb3re153oOBD/QSuDKW/Ebciq+6SKmgfoCGCNLD/hd5be3B95pU8CFUdSsQ6sASCfz7TZ9jM9paeP9iQdHplxo7QCAxxlT2szwn3WJmp7bi8/yQmfcoyxs2bh/eQoio/yZmRBSJjgY/rwXcA5wu1vt0wtYl0weGj64FLQDZnnBR5mQnQ2yPibhiyTaIv1JY1ScXkZm2y99RY8/VoLZqcJBpso4mR7lBCqMAr2FRfo3uScLQIfk17fLP2Cq4XeIbvxKPplUC8/mjLI6eREIbcq0MjruhQeecjviDDe8gOtu1tcu2fbth3AIjNWeu3JFXkryBae4+KMo+YELqf42/f6uogx1tSjedklbJbKXAk8jxP73xEIciHx+vGukoN+6+ZKRuIY+94nkoV39xNlMCjMILdc=
  app: imkerij
  on:
    repo: Lubmes/Imkerij
  skip_cleanup: true
env:
  matrix:
  - s3_bucket='imkerij-poppendamme-dev'
  global:
  - secure: R8lOBc7UdnGeAM5QVW9C8VouGDXLqTVLLISMxZ0SjwT1Ip11zI5oxN1gsHp7bIO4C92ezJu2v+2rO+HLzJlC2F00MgqXXTN+/oloO9lIHZ+XWx0vMZmaZ9hHEtrdcLRJ22HtNYL833gjKrHLvCii2v+22Aiwuhg23MFOfi+bqLY3YLLnKJ6FO8RgV9Vb2dL7nNj/gDLOz3p9A6QtVQhKkCrPeXjk7OGuje2N59HTgrtKwiRyk3aAnVvowG2zwUbOId31A7oIk+hxNTXnKCuVII8lQPseUXoR0Hdg61Z35DH4rdSdtMiMcmgiqXDz2p5Cs0biCRPL6xOeKJ3Di4qppNDbSFsMOVNu8+p39nYoMhuxwAXPNpuIYm3MkSP7oYcPhad7boFrtlTW/mzHbB8+toUnjQ73Bj34SrIZRpAVHGRlmlF9gdUM1jI+aWj3YwcLeQd7IQrjlczzRYx1/kWs2Ckl9uNBhrKCi5lJAu8DvDazm7cYc3euUQmatKWivPvoSWICwbeTUSdLsEZ52sbRqubA3EEZZCwlns9sh5L1A8FCQkbbSkJsnGg/uSB7LWnPObT/g6DGgeoz5WNNLEUAg6YlA52GyxMdJ4IYewyx+ghBo6MibwXnid93RA/qG2TyD/VF2t3LaquOsVif3t5wKgbgS2GWBb25b71dv6+krt8=
  - secure: yQmgbK1er+lb3B/ZYpal6vMIBSiF948KdDyNDG+9PzrLLf6VFP6c6uUFPOBxHszqI9be687xupdpn0bWvqnl2kJBL/rqzjZWRcqJoiIYQZOziypDZbqVaeNoTgYCWQoBeUZGUy2INL/H+9YgVACZgFsL2IMs0xDk73P0R3YVrOvM3hQvuZIKX4oSPqFOZKhd8HQkEAC9THw3lIQiRCDJnkesiOuPuzu4Q9pM7Kpta+KzagQpkZn/cTGdXUw+r0vji3JfwtufyyESesLQflDafkB4iaeOY6h+cVKvD/QRQi+Xzt354bBXakDOM3NP/+sBFiUpSW8PcgpsDj/CaV4mBqMcXw0XdvtG9AhjE0Dbzu3kjnynEacEHjENp3dQdcY5Yn38dl23JrnukPel8U5IZmR5nzrtgb3BXegBY+6FTyx9c6K1Prrb+y+1nO/4Qgmlj7d7i7QPu/h/MV0wrWY8EmJnKpHemrfP+L3dx1N7FtTcLIwwld+bX0tO5ZQeW7AsRMyt6oFMdgyxj2t19sG+73WIigtUb5PfSq0NQFk9IOUNHqUUONQ/pymFyd9TIy05FvNVaex7tokzhuuMT6i40W9bud0BUQt8OFPLM9GACbrskPm7JHa4PUO8zdYkkHx68aZYMpJ5nW5weKjNkcA5J+4hFDylfWjomD2cMvCDQh8=
