language: ruby
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
rvm:
- 2.4.0
bundler_args: "--jobs=2"
script:
- bundle exec rake db:setup
- bundle exec rake spec
cache: bundler
services:
- postgresql
addons:
  postgresql: '9.4'
deploy:
  provider: heroku
  api_key:
    secure: yuQ90XdjxnfNkQv1nYUW7GUXRgJf/kYhrD8VBxl+6H4LSXMRxwSss1TGR51WqKY7xB/HsgckVC5CTJ7Z/Ot0paPwgkK+1yE6Vflyg0Evk1vkXoBp0TjQdld6IWgjh7B/4GjpH2rKmsuRQNHo6YCIf++hN9JeyTo7I5DG8vTCus7CUFIf88i+NtWC9GQXVhKjrEMnmWJJSO9CH3EBD+gjfd+k/iMgA6FeVpf8/snfdR57/V/mrI5KtOS4l8woNC1Ameiiy057YoAakQxPR3Mb3re153oOBD/QSuDKW/Ebciq+6SKmgfoCGCNLD/hd5be3B95pU8CFUdSsQ6sASCfz7TZ9jM9paeP9iQdHplxo7QCAxxlT2szwn3WJmp7bi8/yQmfcoyxs2bh/eQoio/yZmRBSJjgY/rwXcA5wu1vt0wtYl0weGj64FLQDZnnBR5mQnQ2yPibhiyTaIv1JY1ScXkZm2y99RY8/VoLZqcJBpso4mR7lBCqMAr2FRfo3uScLQIfk17fLP2Cq4XeIbvxKPplUC8/mjLI6eREIbcq0MjruhQeecjviDDe8gOtu1tcu2fbth3AIjNWeu3JFXkryBae4+KMo+YELqf42/f6uogx1tSjedklbJbKXAk8jxP73xEIciHx+vGukoN+6+ZKRuIY+94nkoV39xNlMCjMILdc=
  app: imkerij
  on:
    repo: Lubmes/Imkerij
  skip_cleanup: true
env:
  matrix:
  - s3_bucket='imkerij-poppendamme-dev'
  - secure: gsGUhLDG4bBmzbCm4m3EaofHeocOXV2gkjYlJJ2o3NGqxxdHU/p/FK9ZR+PHxE3ZjK41squxpF5iZ+eKvoU9e5xkPhK4kKP2bQfmh59WJ7Dp7uBCc7UfjqVey2Vyq9qM6LQZALuztKSlZVKcGgTbfjfvwLOVNmRktmQ/FCRPuuVxlW+92nyVX/1l3arGlIZ757coCrqIpTx5cFxJv+FHuWiRezTM7Pd7a/0D4Gy0BZdg7OBdDKnn8DonaEC0Fn8vT/55EIRMfmM5vV5HsQaEE4KPgldvaKJVCcgUYOzpo/xyJU+u0CgJmxdY6Gb4HsdjXzXV5jeR+XnjCqLNmqEIrzSgClxM/TokWBMgqjxmq2XQZ5IDnoNAQO+fZGUlwoYcfT6cI8tGZXRe45F7/AiLbV60kLV3dkvIXXol6n/2PXiQzvwG0uzqwGodvA/rOiSKKTBEQyIlpvkP74DZfGHG49c91pHK0IsrZ8h22mcwclvLNmelhhB5x7VQSi1HsAbPsD6WbcAUp2zfgTSYsiogmgPmi4J1yXNLCZknSily+2F6mfzjOUtB3kg5vXXPWMolp7ZM48PzTWWAXUH7kU3gxQVDzrXN+X/899R9OACDaG+9d5d9BgGUZNrcp7HmyLmuTzGv+RE0Pzm4j779w7DKIyAeMqEOsoJ0Nk0JQ6ebAtM=
  - secure: ONz4RpX3+fqOZnLEfRohCVvmLaTGMLb4F/jlxULpJizHKlgHbg3UBU85dT4Iz7RcUv8ybD9E1J+bGvn7PLcwRhSblAQWC2v8eV+d7h8vZD1sV8HMpEq5zY1gKVZDO50QBdVgJ5aArA9pgvjO+T3Mng7stgJ8Xhe21K+fkVo5nKjq5sGX/Ndm7/X5BLTkcmeFMMU4P3SD7gLIu7JFkfvsLHWoEy7USwQAPw70Xml7GOmybyim8CaYlEQzSIwzMhEzClWAj0Umeg3ozQTI3NsJTpC6GnSb1aqS2A3fMgUlFMjKYoti8YTqLYPXFhg3EJujvtsyusOHyUQ91HpHx3qdhw3TWlvsl/YAHuAHIRSLAKJ8XZtjiOBEgIW2xyg2MmYcnldDUcdbDhwdVq25a44CnT/2mfLQImAfICDWrJLayOJp/hYyaW4AETE0IvwRA6+gegowdXvpW4ZMmFH0YiEEqAcGXABWMTfJQXbk6gpwayAHoWkNoyl45VRrXuHFZQkq4gjihSxazgHFxH0uIabnqVO+UCU4r7L/LKkWY9rdgcMAagA5+dT5b0OZh1Snoy8H6oPJelmvrxqyx7wJHQ3PYrH9QIwysdQcXwGupL+zJfO/fsqRCmwX+VbnZEo9QyIhXqiK2zrw8FmoarBitrGWZhmO8CWK1TZGG3pShmJdllE=
